### ISSUE TITLE
Integrate breadcrumb, header, footer changes from vets-website

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/va_common#29]
Update gem to include these changes
- [x] department-of-veterans-affairs/vets-website#2489
- [x] department-of-veterans-affairs/vets-website#2487
- [x] department-of-veterans-affairs/vets-website#2440
- [x] department-of-veterans-affairs/vets-website#2422

Blocks department-of-veterans-affairs/gi-bill-comparison-tool#377
